### ISSUE TITLE
Invalid SENTINEL_HOSTS format

### ISSUE THREAD

**Issue by cezarsa** [tsuru/redisapi#20]
The format the hosts are encoded in the SENTINEL_HOSTS variable is kind of broken.
Right now it's like:
```SENTINEL_HOSTS=[http://redis1.domain, http://redis2.domain]```

Some problems:
* It isn't json because the quotes are missing;
* The protocol for sentinel isn't http;
* There's no REDIS_ prefix in the variable name, this could make it harder to find out who is injecting it.

**Comment by fsouza** [comment]
Actually, redisapi will respect the value of the SENTINEL_HOSTS environment variable defined for it, so we don't need any changes in code!

See: https://github.com/tsuru/redisapi/blob/b970f16a09b0f96e05ac522dc6d237d3014fcca1/redisapi/managers.py#L81
